name: echo-server
enableEchoServer: true

hosts:
  - echo.example.com

upstream:
  host: echo-server
  supportsHttps: false

headers:
  in:
    - example1
    - example2
    - unity-gw-player-id

rateLimiters:
  echo1: 
    - targets:
        - key: ip
        - key: unity-gw-player-id
      limits:
        - unit: second
          limit: 1
        - unit: minute
          limit: 1
  echo2: 
    - targets:
        - key: unity-gw-player-id
      limits:
        - unit: second
          limit: 2
        - unit: minute
          limit: 2

routes:
  - path: /echo
    authentication: false
    methods:
      - GET
    name: echo
    rateLimiters: 
      - "echo1"
      - "echo2"

  - path: /echo2
    authentication: false
    methods:
      - GET
    name: echo2
    rateLimiters: 
      - "echo1"

debug: false
